"""Rail thickness capping (+ carve naming shared with the templates).

cap_rail_thickness_to_wall is a post-snap fixup called from
pipeline.install_rails_for_drawer (so the batch installer and the addon
share it): a snapped rail may penetrate its mounting panel (side wall /
divider). Penetration itself is fine (it gets carved for printing), but
the rail must not poke out of the panel's FAR face. When it does, the rail
is scaled along the width (thickness) axis only, about its inner
(drawer-side) face, so the outer face lands just inside the panel's far
face. Runs after every other scale/snap/coborder step; nothing downstream
re-derives scale from it. Runs BEFORE the drawer is parented to the rail,
so drawer geometry is never squashed.

The boolean cutters themselves ship INSIDE the rail templates as a
`carve_rail_clearance` object (authored once by author_carve.py, exactly
like the hinge templates' `carve_body_clearance`). They load, scale, snap,
mirror, and thickness-cap together with the rail root; install_from_pred
subtracts them from overlapping static body meshes when --carve is on.
"""
from __future__ import annotations

import bpy  # type: ignore
import numpy as np
from mathutils import Matrix, Vector  # type: ignore

# Rail outer face is pulled to this depth inside the panel far face, so the
# capped rail never renders coplanar with the panel.
_PROTRUDE_EPS = 0.0005
# Never squash the rail below this fraction of its snapped thickness.
_MIN_THICKNESS_FRAC = 0.05
# A wall candidate must run along at least this fraction of the rail's
# slide length (rules out back panels and face frames, which only overlap
# the rail's ends).
_MIN_SLIDE_OVERLAP_FRAC = 0.3

# Template cutter object name; instances are `carve_rail_clearance__<joint>_L/R`.
CARVE_PREFIX = "carve_rail_clearance"


def _base_name(name: str) -> str:
    if "." in name and name.rsplit(".", 1)[-1].isdigit():
        name = name.rsplit(".", 1)[0]
    return name.split("__", 1)[0]


def _rail_mesh_objs(root: bpy.types.Object) -> list[bpy.types.Object]:
    """Actual rail mechanism meshes under root (no snap planes, no carves)."""
    out = []
    for o in [root, *root.children_recursive]:
        if o.type != "MESH" or o.data is None:
            continue
        base = _base_name(o.name)
        if base.startswith(("snap_plane", "carve")):
            continue
        out.append(o)
    return out


def _is_in_rail_hierarchy(obj: bpy.types.Object) -> bool:
    cur = obj
    while cur is not None:
        if _base_name(cur.name) in ("rail_master", "rail"):
            return True
        cur = cur.parent
    return False


def _static_wall_objs(exclude: set[str]) -> list[bpy.types.Object]:
    """Static cabinet meshes that can act as a mounting panel. Excludes
    everything that moves or was generated by us."""
    out = []
    for o in bpy.context.scene.objects:
        if o.type != "MESH" or o.data is None or o.name in exclude:
            continue
        if _is_in_rail_hierarchy(o):
            continue
        if o.get("generated_by") == "support_block":
            continue
        low = o.name.lower()
        if ("door" in low or "handle" in low or "hinge" in low
                or "carve" in low or "__validation_temp__" in low):
            continue
        out.append(o)
    return out


def _proj_interval(obj: bpy.types.Object, axis: np.ndarray) -> tuple[float, float]:
    """(min, max) projection of the object's world bound_box corners."""
    M = obj.matrix_world
    vals = [float(np.dot(np.asarray(M @ Vector(c), dtype=float), axis))
            for c in obj.bound_box]
    return min(vals), max(vals)


def _verts_interval(objs: list[bpy.types.Object], axis: np.ndarray) -> tuple[float, float]:
    lo, hi = float("inf"), float("-inf")
    for o in objs:
        M = o.matrix_world
        for v in o.data.vertices:
            p = float(np.dot(np.asarray(M @ v.co, dtype=float), axis))
            lo = min(lo, p)
            hi = max(hi, p)
    return lo, hi


def _local_far_face(wall, w_out, s_axis, h_axis, p_lo,
                    s_range, h_range) -> float | None:
    """Far surface of the wall's FIRST solid slab along w_out, sampled over
    the rail-wall overlap rectangle. Rays start just inside the wall's near
    face and record the first surface exit; the minimum over samples is the
    thinnest local board. None if every ray misses."""
    from mathutils.bvhtree import BVHTree
    deps = bpy.context.evaluated_depsgraph_get()
    try:
        tree = BVHTree.FromObject(wall, deps)
    except Exception:
        return None
    # BVHTree.FromObject lives in the object's LOCAL space (imported PNM
    # meshes carry a 180-degree flip matrix), so rays go through the
    # inverse transform and hits come back through the forward one.
    M = wall.matrix_world
    Minv = M.inverted()
    dir_local = (Minv.to_3x3() @ Vector(w_out)).normalized()
    eps = 0.0005
    hits = []
    s_lo, s_hi = s_range
    h_lo, h_hi = h_range
    n_s, n_h = 5, 3
    for i in range(n_s):
        sv = s_lo + (s_hi - s_lo) * (i + 0.5) / n_s
        for j in range(n_h):
            hv = h_lo + (h_hi - h_lo) * (j + 0.5) / n_h
            origin = Vector((p_lo + eps) * w_out + sv * s_axis + hv * h_axis)
            loc = tree.ray_cast(Minv @ origin, dir_local)[0]
            if loc is not None:
                world_hit = np.asarray(M @ loc, dtype=float)
                hits.append(float(np.dot(world_hit, w_out)))
    return min(hits) if hits else None


def cap_rail_thickness_to_wall(rail, drawer_mesh_objs: list) -> dict:
    """Scale `rail` (a RailSnapResult) along the width axis so its outer
    face does not protrude past the far face of the mounting panel it
    collides with. No-op when the rail does not collide with any wall or
    already stays inside it."""
    pl = rail.placement
    w = np.asarray(pl.width_axis_world, dtype=float)
    w = w / max(np.linalg.norm(w), 1e-12)
    s_axis = np.asarray(pl.slide_axis_world, dtype=float)
    s_axis = s_axis / max(np.linalg.norm(s_axis), 1e-12)

    meshes = _rail_mesh_objs(rail.root)
    if not meshes:
        return {"capped": False, "reason": "no_rail_meshes"}
    # Outward = away from the drawer center, measured, not assumed: the
    # width-axis sign convention differs between the snapped and mirrored
    # rails, and the side label alone has bitten before.
    m_lo, m_hi = _verts_interval(meshes, w)
    d_c = float(np.dot(np.asarray(pl.drawer_center, dtype=float), w))
    sign = 1.0 if (m_lo + m_hi) * 0.5 >= d_c else -1.0
    w_out = sign * w
    h_axis = np.cross(w_out, s_axis)
    r_lo, r_hi = (m_lo, m_hi) if sign > 0 else (-m_hi, -m_lo)
    rs_lo, rs_hi = _verts_interval(meshes, s_axis)
    rh_lo, rh_hi = _verts_interval(meshes, h_axis)
    rail_slide_len = rs_hi - rs_lo
    if r_hi - r_lo < 1e-6 or rail_slide_len < 1e-6:
        return {"capped": False, "reason": "degenerate_rail"}

    exclude = {o.name for o in drawer_mesh_objs}
    best, best_area = None, 0.0
    for o in _static_wall_objs(exclude):
        p_lo, p_hi = _proj_interval(o, w_out)
        # Collision: thickness intervals overlap. Covers both the partial
        # case (rail's outer region penetrates the wall) and containment
        # (a wall thinner than the rail sits fully inside its interval).
        if not (p_lo < r_hi - 1e-6 and p_hi > r_lo + 1e-6):
            continue
        os_lo, os_hi = _proj_interval(o, s_axis)
        oh_lo, oh_hi = _proj_interval(o, h_axis)
        ov_s = min(rs_hi, os_hi) - max(rs_lo, os_lo)
        ov_h = min(rh_hi, oh_hi) - max(rh_lo, oh_lo)
        if ov_s < _MIN_SLIDE_OVERLAP_FRAC * rail_slide_len or ov_h <= 0.0:
            continue
        area = ov_s * ov_h
        if area > best_area:
            best = (o, p_lo, p_hi,
                    (max(rs_lo, os_lo), min(rs_hi, os_hi)),
                    (max(rh_lo, oh_lo), min(rh_hi, oh_hi)))
            best_area = area
    if best is None:
        return {"capped": False, "reason": "no_colliding_wall"}

    wall, p_lo, p_hi, s_range, h_range = best
    # PNM statics are often several boards merged into one mesh (panel +
    # face-frame bars), so the AABB far face can lie way beyond the actual
    # mounting board. Raycast through the wall across the rail's footprint
    # and cap against the LOCAL far surface: the thinnest first-slab exit.
    p_hi_local = _local_far_face(wall, w_out, s_axis, h_axis,
                                 p_lo, s_range, h_range)
    if p_hi_local is not None:
        p_hi = min(p_hi, p_hi_local)
    if r_hi <= p_hi - _PROTRUDE_EPS:
        return {"capped": False, "reason": "inside_panel",
                "wall": wall.name}

    target_hi = p_hi - _PROTRUDE_EPS
    s = (target_hi - r_lo) / (r_hi - r_lo)
    s = max(s, _MIN_THICKNESS_FRAC)
    if s >= 1.0:
        return {"capped": False, "reason": "inside_panel", "wall": wall.name}

    # World-space scale by s along w_out about the plane through the rail's
    # inner face: p' = p + (s-1) * ((p.w_out) - r_lo) * w_out
    L = np.eye(3) + (s - 1.0) * np.outer(w_out, w_out)
    t = (1.0 - s) * r_lo * w_out
    M = Matrix(((L[0][0], L[0][1], L[0][2], t[0]),
                (L[1][0], L[1][1], L[1][2], t[1]),
                (L[2][0], L[2][1], L[2][2], t[2]),
                (0.0, 0.0, 0.0, 1.0)))
    rail.root.matrix_world = M @ rail.root.matrix_world
    bpy.context.view_layer.update()
    return {"capped": True, "wall": wall.name,
            "thickness_scale": s,
            "rail_thickness_mm": (r_hi - r_lo) * 1000,
            "protrusion_mm": (r_hi - p_hi) * 1000,
            "panel_far_face": p_hi}

